export const scenarios = Object.freeze([
  {
    id: 'pass-membership-discount',
    title: 'membership discount applies exactly once',
    expectedVerdict: 'PASS',
    expectedProfile: 'FULL',
    expectedVerificationExitCode: 0,
    expectedReportOutput: 'OK membership discount behavior: member=90 guest=100',
    requiredEvidence: ['R01', 'V01', 'E01'],
    escalationReason: 'default full Phase 1 continuity fixture',
    product: {
      changedPath: 'src/discount.mjs',
      baselineFiles: {
        'README.md': '# Fixture product\n\nRequirement lives in `requirements/membership-discount.md`.\n',
        'requirements/membership-discount.md': [
          '# Authoritative acceptance criterion',
          '',
          'Source or owner: Fixture Product Owner.',
          'Criterion: `applyMembershipDiscount(100, true)` must return `90`, and non-members must keep the original price.',
          'Verification command: `node verify-membership-discount.mjs`.',
          '',
        ].join('\n'),
        'src/discount.mjs': [
          'export function applyMembershipDiscount(price, isMember) {',
          '  return price;',
          '}',
          '',
        ].join('\n'),
        'verify-membership-discount.mjs': [
          'import { applyMembershipDiscount } from "./src/discount.mjs";',
          '',
          'const memberPrice = applyMembershipDiscount(100, true);',
          'const guestPrice = applyMembershipDiscount(100, false);',
          'if (memberPrice !== 90 || guestPrice !== 100) {',
          '  console.error(`membership discount mismatch: member=${memberPrice} guest=${guestPrice}`);',
          '  process.exit(1);',
          '}',
          'console.log("OK membership discount behavior: member=90 guest=100");',
          '',
        ].join('\n'),
      },
      candidateFiles: {
        'src/discount.mjs': [
          'export function applyMembershipDiscount(price, isMember) {',
          '  return isMember ? price * 0.9 : price;',
          '}',
          '',
        ].join('\n'),
      },
      verifyCommand: ['node', 'verify-membership-discount.mjs'],
    },
    prompt: [
      'Run the QA skill workflow against the explicit product target for the membership discount Diff.',
      'Scope: only the changed membership discount behavior and the authoritative criterion in requirements/membership-discount.md.',
      'User requirement: perform a complete QA review rather than a compact check, while still preserving the one-child Phase 1 workflow.',
      'Non-goals: release decision, code changes, network access, dependency installation, and global configuration changes.',
      'Use the project-provided verification command and preserve read-only product behavior.',
    ].join('\n'),
  },
  {
    id: 'fail-rounding-regression',
    title: 'candidate floors cents instead of rounding half up',
    expectedVerdict: 'FAIL',
    expectedProfile: 'FULL',
    expectedVerificationExitCode: 1,
    expectedReportOutput: 'tax rounding defect: expected 10.24 received 10.23',
    requiredEvidence: ['R02', 'V02', 'E02', 'F02'],
    escalationReason: 'ambiguous acceptance and defect classification require Full planning and conclusion',
    product: {
      changedPath: 'src/tax.mjs',
      baselineFiles: {
        'README.md': '# Fixture product\n\nRequirement lives in `requirements/tax-rounding.md`.\n',
        'requirements/tax-rounding.md': [
          '# Authoritative acceptance criterion',
          '',
          'Source or owner: Fixture Finance Owner.',
          'Criterion: `calculateTax(127.94, 0.08)` must return `10.24` using normal cent rounding.',
          'Verification command: `node verify-tax-rounding.mjs`.',
          '',
        ].join('\n'),
        'src/tax.mjs': [
          'export function calculateTax(amount, rate) {',
          '  return Number((amount * rate).toFixed(2));',
          '}',
          '',
        ].join('\n'),
        'verify-tax-rounding.mjs': [
          'import { calculateTax } from "./src/tax.mjs";',
          '',
          'const actual = calculateTax(127.94, 0.08);',
          'if (actual !== 10.24) {',
          '  console.error(`tax rounding defect: expected 10.24 received ${actual}`);',
          '  process.exit(1);',
          '}',
          'console.log("OK tax rounding behavior");',
          '',
        ].join('\n'),
      },
      candidateFiles: {
        'src/tax.mjs': [
          'export function calculateTax(amount, rate) {',
          '  return Math.floor(amount * rate * 100) / 100;',
          '}',
          '',
        ].join('\n'),
      },
      verifyCommand: ['node', 'verify-tax-rounding.mjs'],
    },
    prompt: [
      'Run the QA skill workflow against the explicit product target for the tax rounding Diff.',
      'Scope: only the changed cent-rounding behavior and the authoritative criterion in requirements/tax-rounding.md.',
      'Context: the shared tax helper is consumed by invoice totals and receipt summaries, so classify evidence against those shared-consumer risks without expanding beyond the provided verifier.',
      'Non-goals: release decision, code changes, network access, dependency installation, and global configuration changes.',
      'Use the project-provided verification command and classify a demonstrated behavior mismatch as product evidence, not infrastructure.',
    ].join('\n'),
  },
  {
    id: 'blocked-missing-acceptance-data',
    title: 'critical acceptance data artifact is absent',
    expectedVerdict: 'BLOCKED',
    expectedProfile: 'FULL',
    expectedVerificationExitCode: 2,
    expectedReportOutput: 'missing prerequisite: acceptance-data/currency-cases.json',
    requiredEvidence: ['R03', 'V03', 'E03'],
    escalationReason: 'environment/data prerequisite risk requires Full escalation',
    missingPrerequisite: 'acceptance-data/currency-cases.json',
    rerunCondition: 'Provide acceptance-data/currency-cases.json, then rerun node verify-currency-format.mjs and the affected QA scenario.',
    product: {
      changedPath: 'src/currency.mjs',
      baselineFiles: {
        'README.md': '# Fixture product\n\nRequirement lives in `requirements/currency-format.md`.\n',
        'requirements/currency-format.md': [
          '# Authoritative acceptance criterion',
          '',
          'Source or owner: Fixture Payments Owner.',
          'Criterion: Currency formatting must satisfy every case in the authoritative artifact `acceptance-data/currency-cases.json`.',
          'Critical prerequisite: `acceptance-data/currency-cases.json` is required to define expected results.',
          'Verification command: `node verify-currency-format.mjs` after the prerequisite artifact is supplied.',
          '',
        ].join('\n'),
        'src/currency.mjs': [
          'export function formatCurrency(amount) {',
          '  return `$${amount.toFixed(2)}`;',
          '}',
          '',
        ].join('\n'),
        'verify-currency-format.mjs': [
          'import { existsSync } from "node:fs";',
          '',
          'if (!existsSync("acceptance-data/currency-cases.json")) {',
          '  console.error("missing prerequisite: acceptance-data/currency-cases.json");',
          '  process.exit(2);',
          '}',
          'console.log("Prerequisite present; cases can be checked.");',
          '',
        ].join('\n'),
      },
      candidateFiles: {
        'src/currency.mjs': [
          'export function formatCurrency(amount) {',
          '  return `$${amount.toFixed(2)} USD`;',
          '}',
          '',
        ].join('\n'),
      },
      verifyCommand: ['node', 'verify-currency-format.mjs'],
    },
    prompt: [
      'Run the QA skill workflow against the explicit product target for the currency formatting Diff.',
      'Scope: only the changed currency formatting behavior and the authoritative criterion in requirements/currency-format.md.',
      'Non-goals: release decision, code changes, network access, dependency installation, and global configuration changes.',
      'The acceptance data artifact named by the requirement is authoritative; do not invent expected cases when it is absent.',
    ].join('\n'),
  },
  {
    id: 'lite-static-label-copy',
    title: 'single-module copy label change is lite eligible',
    expectedVerdict: 'PASS',
    expectedProfile: 'LITE',
    expectedVerificationExitCode: 0,
    expectedReportOutput: 'OK profile label behavior: Beta access',
    requiredEvidence: ['R04', 'V04', 'E04'],
    liteEligibility: 'single changed module, explicit acceptance criterion, existing fast verifier, no ambiguity, no cross-module impact, no high-risk permission or environment dependency',
    product: {
      changedPath: 'src/label.mjs',
      baselineFiles: {
        'README.md': '# Fixture product\n\nRequirement lives in `requirements/profile-label.md`.\n',
        'requirements/profile-label.md': [
          '# Authoritative acceptance criterion',
          '',
          'Source or owner: Fixture Content Owner.',
          'Criterion: `profileLabel()` must return `Beta access` for the small copy-only label update.',
          'Verification command: `node verify-profile-label.mjs`.',
          '',
        ].join('\n'),
        'src/label.mjs': [
          'export function profileLabel() {',
          '  return "Beta program";',
          '}',
          '',
        ].join('\n'),
        'verify-profile-label.mjs': [
          'import { profileLabel } from "./src/label.mjs";',
          '',
          'const actual = profileLabel();',
          'if (actual !== "Beta access") {',
          '  console.error(`profile label mismatch: ${actual}`);',
          '  process.exit(1);',
          '}',
          'console.log("OK profile label behavior: Beta access");',
          '',
        ].join('\n'),
      },
      candidateFiles: {
        'src/label.mjs': [
          'export function profileLabel() {',
          '  return "Beta access";',
          '}',
          '',
        ].join('\n'),
      },
      verifyCommand: ['node', 'verify-profile-label.mjs'],
    },
    prompt: [
      'Run the QA skill workflow against the explicit product target for the profile label Diff.',
      'Scope: only the changed single-module copy label behavior and the authoritative criterion in requirements/profile-label.md.',
      'Non-goals: release decision, code changes, network access, dependency installation, global configuration changes, cross-module regression hunting, permissions, and environment provisioning.',
      'Use the project-provided verification command and preserve read-only product behavior.',
    ].join('\n'),
  },
]);

export function scenarioById(id) {
  const scenario = scenarios.find((candidate) => candidate.id === id);
  if (!scenario) {
    throw new Error(`Unknown scenario: ${id}`);
  }
  return scenario;
}
